name 'jeffsheltren-yumrepos'
version '0.3.6'
source 'git@github.com:jeffsheltren/puppet-yumrepos.git'
author 'Jeff Sheltren'
license 'BSD'
summary 'Yum repo definitions for common repos (RHEL/CentOS).'
description 'Provides multiple "yumrepos::reponame" classes used to create yum repos on CentOS/RHEL systems. Classes are parameterized so that common options are easily configurable. Includes GPG keys for repos where available.'
